services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    shm_size: "1gb"

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U departures -d departures"]
      interval: 1s
      timeout: 5s
      retries: 10

    ports:
      - "5432:5432"

  staticmaps:
    image: mxdcodes/docker-staticmaps:latest
    restart: always

    ports:
      - "3000:3000"

  static_server:
    build: frontend
    restart: unless-stopped
    depends_on:
      - api_server
    ports:
      - "6680:80"
    volumes:
      - ./static/gtfs-nl.zip:/usr/share/nginx/html/gtfs-nl.zip

  kv6_ingest:
    build: kv6_ingest
    restart: unless-stopped

    depends_on:
      postgres: 
        condition: service_healthy

    environment:
      BISON_MQ: ${BISON_MQ}
      POSTGRES: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PGSSLMODE: disable
  
  kv6_projector:
    build: kv6_projector
    restart: unless-stopped

    depends_on:
      postgres: 
        condition: service_healthy

    environment:
      POSTGRES: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PGSSLMODE: disable



  gtfs_updater:
    build: gtfs_updater
    restart: unless-stopped

    depends_on:
      postgres: 
        condition: service_healthy
      static_server: 
        condition: service_started

    environment:
      POSTGRES: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      GTFS_URL: ${GTFS_URL}

      PGSSLMODE: disable

  api_server:
    build: api_server
    restart: unless-stopped

    depends_on:
      postgres: 
        condition: service_healthy

    environment:
      SOURCE_REPO: ${SOURCE_REPO}
      POSTGRES: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PGSSLMODE: disable

volumes:
  postgres_data:
