services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U departures -d departures"]
      interval: 1s
      timeout: 5s
      retries: 10

  static_server:
    image: nginx:alpine
    restart: unless-stopped

    depends_on:
      - api_server

    ports:
      - "6680:80"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/html:ro

  kv6_updater:
    build: kv6_updater
    restart: unless-stopped

    depends_on:
      postgres: 
        condition: service_healthy

    environment:
      POSTGRES: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PGSSLMODE: disable

  gtfs_updater:
    build: gtfs_updater
    restart: unless-stopped

    depends_on:
      postgres: 
        condition: service_healthy
      static_server: 
        condition: service_started

    environment:
      POSTGRES: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      GTFS_URL: ${GTFS_URL}

      PGSSLMODE: disable
      #GTFS_URL: https://gtfs.openov.nl/gtfs-rt/gtfs-openov-nl.zip

  api_server:
    build: api_server
    restart: unless-stopped

    depends_on:
      postgres: 
        condition: service_healthy

    environment:
      SOURCE_REPO: ${SOURCE_REPO}
      POSTGRES: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PGSSLMODE: disable

volumes:
  postgres_data:
