/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Query {
  block_code: number;
  data_owner_code: string;
  label: string;
  rank: number;
  route_color: string;
  route_id: string;
  route_short_name: string;
  route_text_color: string;
  stop_id: string;
  subtitle: string;
  type: string;
  vehicle_number: number;
  [k: string]: unknown;
}
