/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RouteTrip {
  block_code: number;
  block_id: string;
  direction_id: number;
  end_stop: string;
  end_stop_name: string;
  end_time: number;
  last_seen: number;
  lat: number;
  lon: number;
  operating_day: string;
  punctuality: number;
  rd_x: number;
  rd_y: number;
  realtime_trip_id: string;
  route_color: string;
  route_id: string;
  route_short_name: string;
  route_text_color: string;
  start_stop: string;
  start_stop_name: string;
  start_time: number;
  status: string;
  trip_headsign: string;
  trip_id: string;
  trip_short_name: string;
  vehicle_number: number;
  [k: string]: unknown;
}
