/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface StopDeparture {
  at_stop: boolean;
  block_code: number;
  headsign: string;
  last_seen: number;
  lat: number;
  lon: number;
  mode: string;
  operating_day: string;
  platform_code: string;
  punctuality: number;
  rd_x: number;
  rd_y: number;
  route_color: string;
  route_id: string;
  route_short_name: string;
  route_text_color: string;
  scheduled_time: number;
  status: string;
  terminal: boolean;
  trip_id: string;
  vehicle_number: number;
  warning: boolean;
  [k: string]: unknown;
}
