/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface StopQuery {
  parent_station: string;
  platform_code: string;
  stop_code: string;
  stop_id: string;
  stop_name: string;
  [k: string]: unknown;
}
