/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface StopRoute {
  route_color: string;
  route_id: string;
  route_short_name: string;
  route_text_color: string;
  [k: string]: unknown;
}
