/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Stop {
  location_type: number;
  parent_station: string;
  platform_code: string;
  stop_code: string;
  stop_id: string;
  stop_lat: number;
  stop_lon: number;
  stop_name: string;
  stop_timezone: string;
  wheelchair_boarding: number;
  zone_id: string;
  [k: string]: unknown;
}
