/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TripStop {
  block_code: number;
  mode: string;
  operating_day: string;
  platform_code: string;
  punctuality: number;
  scheduled_time: number;
  status: string;
  stop_code: string;
  stop_id: string;
  stop_name: string;
  stop_sequence: number;
  vehicle_number: number;
  [k: string]: unknown;
}
