/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Vehicle {
  block_code: number;
  data_owner_code: string;
  last_seen: number;
  lat: number;
  line_planning_number: string;
  lon: number;
  operating_day: string;
  passage_sequence_number: number;
  punctuality: number;
  rd_x: number;
  rd_y: number;
  realtime_trip_id: string;
  reinforcement_number: number;
  route_color: string;
  route_id: string;
  route_short_name: string;
  route_text_color: string;
  status: string;
  trip_headsign: string;
  trip_id: string;
  trip_short_name: number;
  user_stop_code: string;
  vehicle_number: number;
  [k: string]: unknown;
}
